name: "cri plugin integration test after adding wasm"
on:
  push:
    branches:
      - cri-test
      - wasm
      - wasm_image
  pull_request:
    branches:
      - cri-test
      - wasm
      - wasm_image

permissions:  # added using https://github.com/step-security/secure-workflows
  contents: read

jobs:
  mirror:
    name: "cri integration test after adding wasm"
    runs-on: ubuntu-latest
    permissions:
      packages: write

    defaults:
      run:
        working-directory: src/github.com/containerd/containerd

    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: '1.19.6'

      - uses: actions/checkout@v3
        with:
          path: src/github.com/containerd/containerd

      - name: Set env
        shell: bash
        run: |
          echo "GOPATH=${{ github.workspace }}" >> $GITHUB_ENV
          echo "${{ github.workspace }}/bin" >> $GITHUB_PATH

      - name: Install containerd dependencies
        env:
          RUNC_FLAVOR: ${{ matrix.runc }}
          GOFLAGS: -modcacherw
        run: |
          sudo apt-get install -y gperf
          sudo -E PATH=$PATH script/setup/install-seccomp

      - name: Install and containerd
        shell: bash
        run: |
          # clean
          make clean
          # install containerd
          make GO_BUILDTAGS="no_btrfs"

      - name: Cri pull wasm module test
        shell: bash
        run: |
          # start containerd
          sudo ./bin/containerd &
          # test
          cd integration
          sudo "PATH=$PATH" env go test -v -run "TestWasmModuleInCri" . -test.v